using System.Text.Json;

using AgentSprint.Worker.Models;
using AgentSprint.Worker.Options;

using Microsoft.Extensions.Options;

namespace AgentSprint.Worker.Services;

public sealed class WorkerRunLogger
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)
    {
        WriteIndented = true
    };

    private readonly WorkerOptions _options;

    /// <summary>
    /// <para>zh-cn:创建数字员工运行目录记录器。记录器负责按 runId 创建隔离目录，并将 prompt、stdout、stderr、final.md 和 run.json 写入磁盘；调用方传入的敏感值应在进入 prompt 前完成脱敏。</para>
    /// <para>en-us:Creates the digital-worker run-directory logger. The logger creates an isolated directory per runId and writes prompt, stdout, stderr, final.md, and run.json to disk; callers should redact sensitive values before they enter the prompt.</para>
    /// </summary>
    /// <param name="options">
    /// <para>zh-cn:Worker 运行配置。</para>
    /// <para>en-us:Worker runtime options.</para>
    /// </param>
    public WorkerRunLogger(IOptions<WorkerOptions> options)
    {
        _options = options.Value;
    }

    /// <summary>
    /// <para>zh-cn:创建 run 目录并写入 prompt.txt。该方法会确保 RunsRoot 存在，并返回后续 stdout、stderr、final.md 和 run.json 使用的绝对路径。</para>
    /// <para>en-us:Creates the run directory and writes prompt.txt. The method ensures RunsRoot exists and returns absolute paths for stdout, stderr, final.md, and run.json used by later steps.</para>
    /// </summary>
    /// <param name="runId">
    /// <para>zh-cn:平台或本地生成的运行标识。</para>
    /// <para>en-us:Run identifier generated by the platform or locally.</para>
    /// </param>
    /// <param name="prompt">
    /// <para>zh-cn:本次 Codex 执行提示词。</para>
    /// <para>en-us:Prompt for this Codex execution.</para>
    /// </param>
    /// <param name="cancellationToken">
    /// <para>zh-cn:取消令牌。</para>
    /// <para>en-us:Cancellation token.</para>
    /// </param>
    /// <returns>
    /// <para>zh-cn:本次运行产物路径集合。</para>
    /// <para>en-us:Artifact paths for the run.</para>
    /// </returns>
    public async Task<RunPaths> PrepareAsync(string runId, string prompt, CancellationToken cancellationToken)
    {
        var paths = ResolvePaths(runId);
        Directory.CreateDirectory(paths.RunDirectory);
        await File.WriteAllTextAsync(paths.PromptPath, prompt, cancellationToken);

        return paths;
    }

    /// <summary>
    /// <para>zh-cn:按 runId 计算本地运行产物路径，但不创建目录或写入文件。调用方可在启动平台 WorkerRun 前预先上报这些路径，使管理端能立即展示 stdout、stderr、final.md 和 run.json 的预期位置。</para>
    /// <para>en-us:Resolves local artifact paths for a runId without creating directories or writing files. Callers can report these paths before starting the platform WorkerRun so the management side can display the expected stdout, stderr, final.md, and run.json locations immediately.</para>
    /// </summary>
    /// <param name="runId">
    /// <para>zh-cn:平台或本地生成的运行标识。</para>
    /// <para>en-us:Run identifier generated by the platform or locally.</para>
    /// </param>
    /// <returns>
    /// <para>zh-cn:本次运行产物路径集合。</para>
    /// <para>en-us:Artifact paths for the run.</para>
    /// </returns>
    public RunPaths ResolvePaths(string runId)
    {
        var runsRoot = Path.GetFullPath(_options.RunsRoot);
        var runDirectory = Path.Combine(runsRoot, runId);
        return new RunPaths(
            runDirectory,
            Path.Combine(runDirectory, "prompt.txt"),
            Path.Combine(runDirectory, "stdout.log"),
            Path.Combine(runDirectory, "stderr.log"),
            Path.Combine(runDirectory, "final.md"),
            Path.Combine(runDirectory, "run.json"));
    }

    /// <summary>
    /// <para>zh-cn:写入 run.json 运行摘要。摘要只保存运行状态、路径、耗时和错误概要，不写入 Agent Token、API Key 或其他 Secret。</para>
    /// <para>en-us:Writes the run.json manifest. The manifest stores only run status, paths, duration, and an error summary, and does not write Agent Token, API keys, or other secrets.</para>
    /// </summary>
    /// <param name="paths">
    /// <para>zh-cn:运行产物路径集合。</para>
    /// <para>en-us:Run artifact paths.</para>
    /// </param>
    /// <param name="manifest">
    /// <para>zh-cn:运行摘要。</para>
    /// <para>en-us:Run manifest.</para>
    /// </param>
    /// <param name="cancellationToken">
    /// <para>zh-cn:取消令牌。</para>
    /// <para>en-us:Cancellation token.</para>
    /// </param>
    public async Task WriteManifestAsync(RunPaths paths, WorkerRunManifest manifest, CancellationToken cancellationToken)
    {
        var json = JsonSerializer.Serialize(manifest, JsonOptions);
        await File.WriteAllTextAsync(paths.ManifestPath, json, cancellationToken);
    }
}

public sealed record RunPaths(
    string RunDirectory,
    string PromptPath,
    string StdoutPath,
    string StderrPath,
    string FinalPath,
    string ManifestPath);
